/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package twitter;

import twitter.Exceptions.TwitterServiceException;
import twitter.Interface.TwitterService;
import twitter.Service.TwitterServiceImpl;

public class Twitter {
    public static void main(String[] args) {
        try {
            TwitterService twitter = new TwitterServiceImpl();
            // Print all of these
            twitter.postTweet(1, 1);
            twitter.postTweet(2, 2);
            twitter.postTweet(3,3);
            twitter.getNewsFeed(1);
            twitter.follow(1,2);
            twitter.getNewsFeed(1);
            twitter.getNewsFeed(2);
            twitter.follow(2,3);
            twitter.getNewsFeed(2);
            twitter.unfollow(2,3);
        } catch (TwitterServiceException e) {
            e.printStackTrace();
        }
    }
}
